default:
  outputs:
    dev:
      account: cvbxtzt-nj53246
      database: raw
      password: Shroud1==++
      role:
      schema:
      threads: 4
      type: snowflake
      user: shrestic
      warehouse: transforming
  target: dev
